server:
  port: 8888

spring:
  application:
    name: discoveryserver
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8888/eureka
